version: "2"
services:
  app_cron:
    image: damlys/webdock-api:${APP_VERSION}
    depends_on:
      - mysql
      - redis
    env_file:
      - .env
    command: ["--start-cron"]

  app_web:
    image: damlys/webdock-api:${APP_VERSION}
    depends_on:
      - mysql
      - redis
    env_file:
      - .env

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  redis:
    image: redis:latest
    command: ["--requirepass", "${REDIS_PASSWORD}"]
